# Generated by Django 3.1.7 on 2021-03-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20210322_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='id',
        ),
        migrations.AddField(
            model_name='list',
            name='listID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDisplayName', models.CharField(max_length=200)),
                ('profileLink', models.CharField(max_length=200)),
                ('reputation', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('tagName', models.CharField(max_length=200)),
                ('answerScore', models.IntegerField()),
                ('questionScore', models.IntegerField()),
                ('listID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lists.list')),
            ],
        ),
    ]
