# Generated by Django 3.1.7 on 2021-03-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20210322_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='answerScore',
            new_name='answerScor',
        ),
    ]
