# Generated by Django 3.1.7 on 2021-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20210419_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='profileImage',
            field=models.CharField(default='https://www.gravatar.com/avatar/64323e6cf08401474da3bf770ea13b58?s=128&d=identicon&r=PG&f=1', max_length=200),
            preserve_default=False,
        ),
    ]
