# Generated by Django 3.1.7 on 2021-04-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_userlist_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='records',
        ),
    ]
