# Generated by Django 3.1.7 on 2021-04-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20210420_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='userListID',
            new_name='id',
        ),
    ]
