# Generated by Django 3.1.7 on 2021-04-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20210420_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='bronzeCount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlist',
            name='goldCount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlist',
            name='silverCount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
